# Introductie

Jim Albert heeft zich de afgelopen jaren actief bezig gehouden met de vraag hoe je studenten introduceert in statische denken. Hoe moeten we hen dit leren en hoe moet een nieuwe praktijk eruit zien. Hijzelf is Bayesiaan en vindt dat nieuwe generaties hierin opgeleid moeten worden. Zijn nieuwe boek @albert2020a biedt hier een raamwerk voor. De voorheen strikte voorwaarden laten ze wat vieren hierin; enkele fundamentele concepten moeten studenten hierbij begrijpen; de computer wordt hierbij volop gebruikt; de context wordt erbij gehaald om de motivatie voor statistische concepten te verhogen; en het gaat om op onderzoek-gebaseerd leren. Bovenal is het goed dat er in de opzet aandacht is voor Bayes. Misschien wel vooral omdat deze benadering meer intuïtief is en meer recht-toe-recht-aan dan de klassieke, frequentistische benadering. Studenten wat mee geven vanuit Bayesiaanse perspectief is, zo is hun ervaring, allicht de beste manier om studenten te onderwijzen door zelf onderzoek te doen.

Het boek bestaan uit twee delen. Het eerste deel (hoofdstuk 1 tot en met 6) vertelt iets over waarschijnlijkheid en zaken die daarmee te maken hebben (waaronder voorwaardelijke waarschijnlijkheid, distributies) en ze leren omgaan met `R`. Het hele Bayesiaanse gedeelte zit in hoofdstuk 7 tot en met 13. Hierin aandacht voor de prior, de likelihood en de posterior. Met simulatietechnieken, maar ook voor inferentie, voorspelling, model checken. Lineaire, logistische en poisson modellen komen aan de orde en ook multilevel modellen. Het boek gaat vergezeld van videopresentaties en slide-presentaties die voor iedereen toegankelijk zijn. Het is een eigenwijze tour-de-force waar we de grootste waardering voor moeten hebben. 


In het boek gebruiken Albert en Hu met name het programma `JAGS`. De laatste jaren is `Stan`steeds populairder geworden. Hierin wordt op een andere manier Bayesiaanse modellen met MCMC gefit. In de tutorial @albert2020b laat hij zien hoe je met `Stan`kunt werken en gebruikt hier de interface `Brms` voor. In dit boekje heb ik een deel van zijn tutorial bewerkt.
